### ISSUE TITLE
While formatting the hadoop, got the error. Can you help me out from this.

### ISSUE THREAD

**Issue by saisudheer2419** [atozknowledge/bigdata#4]
[hadooplog.txt](https://github.com/user-attachments/files/16403014/hadooplog.txt)

2024-07-28 16:12:23,954 INFO namenode.FSNamesystem: Retry cache will use 0.03 of total heap and retry cache entry expiry time is 600000 millis
2024-07-28 16:12:23,958 INFO util.GSet: Computing capacity for map NameNodeRetryCache
2024-07-28 16:12:23,958 INFO util.GSet: VM type       = 64-bit
2024-07-28 16:12:23,958 INFO util.GSet: 0.029999999329447746% max memory 860.5 MB = 264.3 KB
2024-07-28 16:12:23,958 INFO util.GSet: capacity      = 2^15 = 32768 entries
2024-07-28 16:12:24,038 INFO namenode.FSImage: Allocated new BlockPoolId: BP-722371022-127.0.1.1-1722163344016
2024-07-28 16:12:24,042 WARN namenode.NameNode: Encountered exception during format: 
java.io.IOException: Cannot create directory /home/username/hadoop2-dir/namenode-dir/current
	at org.apache.hadoop.hdfs.server.common.Storage$StorageDirectory.clearDirectory(Storage.java:436)
	at org.apache.hadoop.hdfs.server.namenode.NNStorage.format(NNStorage.java:579)
	at org.apache.hadoop.hdfs.server.namenode.NNStorage.format(NNStorage.java:601)
	at org.apache.hadoop.hdfs.server.namenode.FSImage.format(FSImage.java:173)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:1190)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1631)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1741)
2024-07-28 16:12:24,053 ERROR namenode.NameNode: Failed to start namenode.
java.io.IOException: Cannot create directory /home/username/hadoop2-dir/namenode-dir/current
	at org.apache.hadoop.hdfs.server.common.Storage$StorageDirectory.clearDirectory(Storage.java:436)
	at org.apache.hadoop.hdfs.server.namenode.NNStorage.format(NNStorage.java:579)
	at org.apache.hadoop.hdfs.server.namenode.NNStorage.format(NNStorage.java:601)
	at org.apache.hadoop.hdfs.server.namenode.FSImage.format(FSImage.java:173)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:1190)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1631)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1741)
2024-07-28 16:12:24,057 INFO util.ExitUtil: Exiting with status 1: java.io.IOException: Cannot create directory /home/username/hadoop2-dir/namenode-dir/current
2024-07-28 16:12:24,148 INFO namenode.NameNode: SHUTDOWN_MSG: 
/************************************************************
SHUTDOWN_MSG: Shutting down NameNode at sai-VMware-Virtual-Platform/127.0.1.1
************************************************************/
sai@sai-VMware-Virtual-Platform:~/hadoop-3.1.0$

**Comment by senthil-2003** [comment]
did you solved it?
